### ISSUE TITLE
Segmentation fault:11

### ISSUE THREAD

**Issue by ZachNikolakis** [thamala/PBScan#1]
Dr. Thamala,

I'm trying to use your program but I keep getting the error Segmentation fault:11.
Here is the output I've been getting
Started with parameters:
	-vcf samtools/Lut_Vir_Nun_05missing.vcf
	-pop1 popmap/C.o.lutosus_popPBS.txt
	-pop2 popmap/C.v.nuntius_pot_newPBS.txt
	-pop3 popmap/C.v.viridis_remove_pot_nunPBS.txt
	-out Lut_Vir_Nun_output
	-win 1000000
	-step 1000000
	-div 2
	-min 2
	-maf 0.05

Reading input files...

Read 12197 sites
Read 88 individuals

Estimating PBS with Dxy...

Segmentation fault: 11

Any help on the issue is appreciated. 

Best,
Zach

**Comment by thamala** [comment]
Sorry for late reply, I somehow missed this question. Earlier there was a bug in VCF parsing, which is now fixed. However, it appears your data is successfully read in so that's not the issue. Currently the program uses SNP-based window sizes and in your case the window size exceeds the total number of SNPs (12197 vs 1000000). If you truly want to get only a single estimate across all sites, I suggest that you leave out the window parameters, estimate PBS for each site and average them across sites. I'll implement a lenght-based window analysis into the program in the near future.

**Comment by Okompath** [comment]
Hi all, 
i am experiencing the same issue with version 2020.03.16. 

i am running this on a SLURM cluster and i am met with this output:

```
PBScan version 2020.03.16

Started with parameters:
        -likes /users/o/k/okompath/Sporothrix/PBScan/PBScan/example_data/sporo_beagle/sporo_beagle.beagle
        -pop1 sporo_sch_pop1.txt
        -pop2 sporo_bra_pop2.txt
        -pop3 sporo_glo_pop3.txt
        -out sporo_spp_pbs
        -div 0
        -min 5
        -maf 0.05

Reading input files...

^[[A^HRead 4237987 sites
Read 117 individuals

Estimating PBS with Hudson's Fst...

Segmentation fault (core dumped)

```
I have also tried with and without window size and step size, and I am unsure where the issue is coming from.

**Comment by cidrahammoud** [comment]
Hi all,

I'm currently experiencing the same error even without any window size specified. Any update or help on this please? 

Thanks!
